# Generated by Django 4.0.2 on 2022-02-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(verbose_name='Новый прайс')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Новый прайс',
                'verbose_name_plural': 'Новые прайсы',
            },
        ),
        migrations.CreateModel(
            name='PriceExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
