# Generated by Django 4.0.2 on 2022-02-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.DeleteModel(
            name='PriceExit',
        ),
    ]
