# Generated by Django 4.0.2 on 2022-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_exitprice_delete_priceexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(verbose_name='Флаг страны')),
                ('color', models.TextField(verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Глобальные установки',
                'verbose_name_plural': 'Глобальные установки',
            },
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(help_text='16, 16гб, 16gb, 16гб...', verbose_name='Память')),
                ('series_prefix', models.TextField(help_text='11 pro, 11 pro max...', verbose_name='Модели с префиксом')),
                ('series_not_prefix', models.TextField(help_text='6, 7, 8, 11, 12, 13', verbose_name='Модели без префикса и букв')),
                ('extra_iphone', models.TextField(help_text='se, sr, x, xs', verbose_name='Extra модели')),
                ('full_name', models.TextField(help_text='iphone 8, iphone x, iphone 11', verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'iPhone',
                'verbose_name_plural': 'iPhone',
            },
        ),
        migrations.RemoveField(
            model_name='prices',
            name='name',
        ),
        migrations.DeleteModel(
            name='ExitPrice',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
