# Generated by Django 4.0.2 on 2022-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_global_iphone_remove_prices_name_delete_exitprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_models', models.CharField(max_length=10, verbose_name='Устройство')),
                ('markup', models.SmallIntegerField(verbose_name='Процент наценки')),
                ('flag', models.BooleanField(default=False, verbose_name='Счет в процентах?')),
                ('markup_int', models.SmallIntegerField(null=True, verbose_name='Наценка в рублях')),
            ],
            options={
                'verbose_name': 'Наценка',
                'verbose_name_plural': 'Наценки',
            },
        ),
    ]
