# Generated by Django 4.0.2 on 2022-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(help_text='16, 16гб, 16gb, 16гб...', verbose_name='Память')),
                ('series', models.TextField(help_text='iPad, iPad pro...', verbose_name='Серии')),
                ('names', models.TextField(help_text='Wi-Fi + Cellular...', verbose_name='WiFi')),
                ('numbers', models.TextField(help_text='12.9, 11', verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'iPad',
                'verbose_name_plural': 'iPad',
            },
        ),
        migrations.CreateModel(
            name='MacBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(help_text='16, 16гб, 16gb, 16гб...', verbose_name='Память')),
                ('series', models.TextField(help_text='MacBook, MacBook Pro...', verbose_name='Серии')),
                ('names', models.TextField(help_text='M1', verbose_name='WiFi')),
                ('extra', models.TextField(help_text='MacBook 11, MacBook Pro 12', verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'MacBook',
                'verbose_name_plural': 'MacBook',
            },
        ),
        migrations.CreateModel(
            name='MacBook1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(help_text='16, 16гб, 16gb, 16гб...', verbose_name='Память')),
                ('series', models.TextField(help_text='MacBook, MacBook Pro...', verbose_name='Серии')),
                ('names', models.TextField(help_text='M1', verbose_name='ХЗ чо это')),
                ('extra', models.TextField(help_text='MacBook 11, MacBook Pro 12', verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'MacBook',
                'verbose_name_plural': 'MacBook',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField(help_text='44mm, 45mm', verbose_name='Размер')),
                ('size_exists', models.TextField(help_text='44,45', verbose_name='Размер без mm')),
                ('series', models.TextField(help_text='5,6,7...', verbose_name='Серии')),
                ('series_full_names', models.TextField(help_text='Series 3, Series 4', verbose_name='Серии')),
                ('extra', models.TextField(help_text='SE...', verbose_name='Extra имена')),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watch',
            },
        ),
    ]
