# Generated by Django 4.0.2 on 2022-04-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_specialcharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcharacter',
            name='new_variant',
            field=models.CharField(max_length=30, verbose_name='Вариант на сайте'),
        ),
    ]
