<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-13 01:36
=======
# Generated by Django 3.2.12 on 2022-04-13 02:21
>>>>>>> origin/main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
    ]
