# Generated by Django 4.0.2 on 2022-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tests',
            field=models.CharField(choices=[('Ростест🇷🇺', 'Ростест🇷🇺'), ('Не Ростест', 'Не Ростест')], default='Не Ростест', max_length=10, verbose_name='Ростест'),
        ),
    ]
