# Generated by Django 4.0.2 on 2022-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0002_product_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tests',
            field=models.BooleanField(default=False, verbose_name='Ростест?'),
        ),
    ]
