# Generated by Django 4.0.2 on 2022-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0005_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='works',
            field=models.TextField(blank=True, help_text='Оставить поле пустым, если не нужно', null=True, verbose_name='Произведенные работы'),
        ),
    ]
