# Generated by Django 4.0.2 on 2022-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0006_alter_product_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_tmp',
            field=models.CharField(default=1, max_length=50, verbose_name='Фоновое имя'),
            preserve_default=False,
        ),
    ]
