# Generated by Django 4.0.2 on 2022-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0009_bookingproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActualPrice',
        ),
        migrations.AlterModelOptions(
            name='seriescategory',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.RemoveField(
            model_name='bookingproduct',
            name='day_created',
        ),
        migrations.AddField(
            model_name='product',
            name='up_price',
            field=models.BooleanField(default=False, verbose_name='Цена поднята?'),
        ),
    ]
