# Generated by Django 4.0.2 on 2022-03-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0010_delete_actualprice_alter_seriescategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relize',
            field=models.BooleanField(default=False, verbose_name='Релизное устройство?'),
        ),
    ]
