# Generated by Django 4.0.2 on 2022-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0011_product_relize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider_device',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Поставщик, если есть'),
        ),
    ]
