# Generated by Django 4.0.2 on 2022-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0013_remove_product_relize_alter_product_provider_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider_device',
            field=models.CharField(blank=True, choices=[('Устройсво клиента', 'Устройсво клиента'), ('Илья Савичев', 'Илья Савичев'), ('Эмиль', 'Эмиль')], default='Устройсво клиента', max_length=50, null=True, verbose_name='Поставщик, если есть'),
        ),
    ]
