# Generated by Django 4.0.2 on 2022-03-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0016_alter_product_provider_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Допущен к публикации?'),
        ),
    ]
