# Generated by Django 4.0.2 on 2022-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30, verbose_name='Устройство')),
                ('series', models.CharField(max_length=30, verbose_name='Серия')),
                ('memory', models.CharField(max_length=30, verbose_name='Память')),
                ('cost', models.CharField(max_length=30, verbose_name='Цена')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('region', models.CharField(max_length=30, verbose_name='Регион')),
                ('extra', models.CharField(max_length=30, verbose_name='Исходная строка')),
            ],
        ),
    ]
