# Generated by Django 4.0.2 on 2022-03-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщик',
            },
        ),
        migrations.AlterModelOptions(
            name='detailmodel',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2022-03-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='new_line',
            field=models.CharField(default=1, max_length=255, verbose_name='Строка состояния'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='provider',
            field=models.CharField(default=1, max_length=25, verbose_name='Поставщик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailmodel',
            name='extra',
            field=models.CharField(max_length=255, verbose_name='Исходная строка'),
        ),
        migrations.CreateModel(
            name='NewPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(verbose_name='Новый прайс')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Поставщик', to='cost_models.providermodel')),
            ],
            options={
                'verbose_name': 'Новый прайс',
                'verbose_name_plural': 'Новый прайс',
            },
        ),
    ]
