# Generated by Django 4.0.2 on 2022-03-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0002_providermodel_alter_detailmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailmodel',
            options={'verbose_name': 'Цены | Поиск', 'verbose_name_plural': 'Цены | Поиск'},
        ),
        migrations.AlterModelOptions(
            name='newpricemodel',
            options={'verbose_name': 'Новый прайс | Управление cvs файлом', 'verbose_name_plural': 'Новый прайс | Управление cvs файлом'},
        ),
    ]
